### ISSUE TITLE
MIP2 Checklist

### ISSUE THREAD

**Issue by PengXing** [mip-project/mip#20]
**5月 18 日的 Checklist**

- [ ] 组件核心机制
- [ ] 完全兼容 MIP1
- [ ] 多 MIP 页，采用单页渲染，打造 SPA 体验
- [ ] 支持 App Shell
- [ ] 支持多页共享 state
- [ ] 升级 MIP 的 Validate
- [ ] MIP2 页面运行在沙盒中
- [ ] 支持开发者在 MIP 页面中编写 JS 操作 state

**6月 18日的 Checklist**
- [ ] 优化资源加载方式，无需站长添加引用
- [ ] MIP Cache 渲染第一级，MIP2 组件反解
- [ ] 支持开发者基于 MIP2 开发整站，而不只是组件
- [ ] 支持 `mip2 deploy` 部署静态站点
- [ ] 支持 `mip2 publish` 发布组件

**后续规划，时间未定**
- [ ] 支持 `mip2 deploy bce` 一键发布到百度云，托管为静态站点

**Comment by PengXing** [comment]
支持多页共享 state 做完了？是不是需要和 @ccksfh 商量该怎么设计？

**Comment by PengXing** [comment]
第一期（5.18）依托于 MIP2 的组件开发机制，暂时不需要北京的同学参与，第二期需要北京同学参与下面会列出 MIP2 第二期的时间节点和人员安排

1. 完全兼容 MIP1
人员：@huanghuiquan @zhangzhiqiang37 @pengxing
时间：5.25
2. 完成 MIP2 的文档编写
人员：@ all
时间：5.25
3. 完成一个 Showcase
人员： @chenqiushi @clark-t 
时间：
4. 搜索侧支持 MIP2 的页面切换
人员： @easonyq 北京的同学
时间：
5. 优化资源加载方式，无需站长添加引用
人员：@clark-t 北京的同学
时间：
6. 性能优化，MIP Cache 渲染第一级，MIP2 组件反解
人员： @xiaoiver OP 北京的同学
时间：
7. 支持开发者基于 MIP2 开发整站，而不只是组件
人员： @clark-t @chenqiushi 
时间：
8. 支持 `mip2 publish` 发布组件
人员： @chenqiushi 
时间：
9. 迁移 MIP1 所有内置组件
人员：北京的同学
时间：
10. 同步支持 AMP，MIP 不支持的组件
人员：北京的同学
时间：
11. 梳理 MIP1 的哪些功能在 MIP2 中去掉，哪些可以保留
人员： @huanghuiquan @zhangzhiqiang37  北京的同学
时间：

**Comment by windtalkers** [comment]
我认为这里的安排基本上没有问题啊，就是看人和排期了，我们再约时间开个会来明确一下好了
